name: Call Docker Container Action (.NET Core)

on: workflow_dispatch

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: call netcore-action
        uses: oaviles/container_action@v2
