name: Manual Deployment Web Apps CI/CD

on:
  workflow_dispatch:
    

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_FLOWER_012038310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
  
  upload_a_build_artifact:
    runs-on: ubuntu-latest
    name: Upload a Build Artifact
    steps:
      - uses: actions/upload-artifact@main
        with:
        # Artifact name
          name: static-web-app-demo
          # A file, directory or wildcard pattern that describes what to upload
          path: public/
          # The desired behavior if no files are found using the provided path
          retention-days: 1
