name: Orchestrator Workflow

on: workflow_dispatch

jobs:
  # ------- Main Orchestration  ---------------
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Microservice
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build Microservice'
          
  test:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: build
    steps:
      - name: Test Microservice
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test Microservice'
  
  dev-environment:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: test
    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy Dev Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
  qa-environment:
    if: ${{ success() }}
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy QA Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
  prod-environment:
    if: ${{ success() }}
    needs: integration-teting-qa-env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - region-1: east
            site: "EastUS"
            datacenter: "site-east"
          - region-2: west
            site: "WestUS"
            datacenter: "site-west"      

    steps:
      - name: Deploy IaC 
        env:
          SITE: ${{ matrix.site }}
          DATACENTER: ${{ matrix.datacenter }}
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy Prod Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
 # ------- Main Orchestration  End ---------------
 
 # ------- If Fail a job ---------------

  create-issue-build:
    if: ${{ failure() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build Fail'
          
  create-issue-test:
    if: ${{ failure() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Test Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test Fail'

  create-issue-dev-env:
    if: ${{ failure() }}
    needs: dev-environment
    runs-on: ubuntu-latest
    steps:
      - name: Dev Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Create Issue Dev Env deployment Fail'
  
  create-issue-qa-env:
    if: ${{ failure() }}
    needs: integration-teting-qa-env
    runs-on: ubuntu-latest
    steps:
      - name: QA Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Create Issue QA Env deployment Fail'
          
  create-issue-prod-env:
    if: ${{ failure() }}
    needs: [run-load-testing-prod-env, integration-teting-prod-env]
    runs-on: ubuntu-latest
    steps:
      - name: Production Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Create Issue Production Env deployment Fail'
  
  # ------- If Fail a job End ---------------
  
  # ------- Testing ---------------
  
  run-load-testing-prod-env:
    if: ${{ success() }}
    needs: prod-environment
    runs-on: ubuntu-latest
    steps:
      - name: Production Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Run Load Testing on Production Env'
          
  integration-teting-prod-env:
    if: ${{ success() }}
    needs: [prod-environment]
    runs-on: ubuntu-latest
    steps:
      - name: Integration Testing on Production Env
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Integration Testing'
          
  integration-teting-qa-env:
    if: ${{ success() }}
    needs: [qa-environment]
    runs-on: ubuntu-latest
    steps:
      - name: Integration Testing on QA Env
        uses: oaviles/javascript_action@v1.3
        with:
          message1: 'Integration Testing QA'
          
   # ------- Testing End ---------------
          
