name: Orchestrator Workflow

on: workflow_dispatch

jobs:
  dev-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy Dev Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
  qa-environment:
    if: ${{ success() }}
    needs: dev-environment
    runs-on: ubuntu-latest

    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy QA Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
  prod-environment:
    if: ${{ success() }}
    needs: qa-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - region-1: east
            site: "EastUS"
            datacenter: "site-east"
          - region-2: west
            site: "WestUS"
            datacenter: "site-west"      

    steps:
      - name: Deploy IaC 
        env:
          SITE: ${{ matrix.site }}
          DATACENTER: ${{ matrix.datacenter }}
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy Prod Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'

  create-issue-dev-env:
    if: ${{ failure() }}
    needs: dev-environment
    runs-on: ubuntu-latest
    steps:
      - name: Dev Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Create Issue Dev Env deployment Fail'
  
  create-issue-qa-env:
    if: ${{ failure() }}
    needs: qa-environment
    runs-on: ubuntu-latest
    steps:
      - name: QA Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Create Issue QA Env deployment Fail'
          
  run-load-testing-prod-env:
    if: ${{ success() }}
    needs: prod-environment
    runs-on: ubuntu-latest
    steps:
      - name: Production Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Run Load Testing on Production Env'
          
  create-issue-prod-env:
    if: ${{ failure() }}
    needs: prod-environment
    runs-on: ubuntu-latest
    steps:
      - name: Production Env deployment Fail
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Create Issue Production Env deployment Fail'
          
          
  integartion-teting-prod-env:
    if: ${{ success() }}
    needs: [prod-environment, dev-environment, qa-environment]
    runs-on: ubuntu-latest
    steps:
      - name: Integration Testing on Production Env
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Integration Testing'
          
