name: Orchestrator Workflow

on: workflow_dispatch

jobs:
  dev-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy Dev Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
  qa-environment:
    if: ${{ failure() }}
    needs: dev-environment
    runs-on: ubuntu-latest

    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy QA Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
          
  prod-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy IaC 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy IaC'
    
    
      - name: Build 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Build'
        
      - name: Test 
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Test'
          
      - name: Deploy Prod Enviroment
        id: javascriptaction
        uses: oaviles/javascript_action@v1.1
        with:
          message: 'Deploy Dev Env'
